trigger:
  - develop

pr:
  branches:
    exclude:
      - '*'

resources:
  - repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
      curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
      sudo apt-get update
      sudo apt-get install -y sbt
    displayName: Install SBT
  - script: sbt publish
    env:
      MAVEN_USER: $(mavenUser)
      MAVEN_PASSWORD: $(mavenPassword)
    displayName: Publish
